#!/usr/bin/env python3
"""Vendor the site's webfonts so rendered pages have no Google Fonts dependency.

The generated CSS keeps Google Fonts' unicode-range splitting. Browsers therefore
download only the WOFF2 slices needed by a page instead of the entire CJK font.
"""

from __future__ import annotations

import hashlib
import re
import shutil
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.request import Request, urlopen


ROOT = Path(__file__).resolve().parent.parent
STATIC_DIR = ROOT / "static"
FONTS_DIR = STATIC_DIR / "fonts"
CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Noto+Serif+SC:wght@300..700&"
    "family=Source+Serif+4:ital,opsz,wght@0,8..60,400..600;"
    "1,8..60,400..500&display=swap"
)
LICENSE_URLS = {
    "OFL-Noto-Serif-SC.txt": (
        "https://raw.githubusercontent.com/google/fonts/main/ofl/notoserifsc/OFL.txt"
    ),
    "OFL-Source-Serif-4.txt": (
        "https://raw.githubusercontent.com/google/fonts/main/ofl/sourceserif4/OFL.txt"
    ),
}
FONT_URL_RE = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+)\)")
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 Chrome/126 Safari/537.36"
)


def _download(url: str) -> bytes:
    request = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(request, timeout=60) as response:
        return response.read()


def main() -> None:
    css = _download(CSS_URL).decode("utf-8")
    urls = list(dict.fromkeys(FONT_URL_RE.findall(css)))
    if not urls:
        raise RuntimeError("Google Fonts CSS contained no downloadable font URLs")

    tmp_dir = Path(tempfile.mkdtemp(prefix=".fonts-", dir=STATIC_DIR))
    try:
        local_names: dict[str, str] = {}
        with ThreadPoolExecutor(max_workers=12) as pool:
            downloads = list(pool.map(_download, urls))
        for url, data in zip(urls, downloads, strict=True):
            if not data.startswith(b"wOF2"):
                raise RuntimeError(f"Downloaded asset is not WOFF2: {url}")
            digest = hashlib.sha256(data).hexdigest()[:16]
            name = f"{digest}.woff2"
            (tmp_dir / name).write_bytes(data)
            local_names[url] = name

        local_css = FONT_URL_RE.sub(
            lambda match: f"url('./{local_names[match.group(1)]}')", css
        )
        header = (
            "/* Generated by scripts/vendor_fonts.py. Font files are served from "
            "this site. */\n"
        )
        (tmp_dir / "fonts.css").write_text(header + local_css, encoding="utf-8")

        for name, url in LICENSE_URLS.items():
            license_text = _download(url).decode("utf-8")
            if "SIL OPEN FONT LICENSE" not in license_text.upper():
                raise RuntimeError(f"Unexpected font license contents: {url}")
            (tmp_dir / name).write_text(license_text, encoding="utf-8")

        if FONTS_DIR.exists():
            shutil.rmtree(FONTS_DIR)
        tmp_dir.replace(FONTS_DIR)
    except Exception:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        raise

    total = sum(path.stat().st_size for path in FONTS_DIR.glob("*.woff2"))
    print(f"Vendored {len(urls)} WOFF2 files ({total / 1024 / 1024:.2f} MiB)")


if __name__ == "__main__":
    main()
